### ISSUE TITLE
fix: undo scoped base font CSS rules to prevent overwriting default HTML styles

### ISSUE THREAD

**Issue by carriquiry-g** [DesarrolloORT/ngx-whats-new#36]
### Description

```scss
:host {
  ...

  * {
    font-size: var(--wn-base-font-size);
    font-family: var(--wn-base-font-family);
  }
}
```

Este fragmento de código hace que las reglas `font-size` y `font-family` tengan prioridad sobre cualquier estilo por defecto del navegador o de etiquetas HTML con estilos particulares como `<small>`.

### Reproduction steps

1. Generar una slide para `ngx-whats-new` que en la propiedad `html` contenga una etiqueta `<small>`
2. Visualizar estilos

### Expected Behavior

El texto renderizado dentro de la etiqueta `<small>` debería tener la regla `font-size: smaller;` aplicada

### Actual Behavior

El texto renderizado dentro de la etiqueta `<small>` se ve como cualquier texto de párrafo y tiene la regla `font-size: var(--wn-base-font-size);` que se impone por especifidad.

### Aditional information

![image](https://github.com/user-attachments/assets/eef2000d-1351-40cc-b3d0-a480eb1954a3)
